databases:
  - name: celebrange database
    databaseName: celebrange database
    user: celebrange

services:
  - type: web
    name: celebrange
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: celebrange
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false